//go:build ignore

// Gen writes tables.go from the Unicode character database: the mirrored
// glyphs and the paired brackets. The bidi classes themselves come from
// golang.org/x/text, so the database is the version those tables were built
// from, and the two cannot drift apart when the module is upgraded:
//
//	go run gen.go                  # fetch from unicode.org
//	go run gen.go -ucd ~/ucd/15.0  # or read a local copy
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"path"
	"sort"
	"strconv"
	"strings"

	xbidi "golang.org/x/text/unicode/bidi"
)

var (
	ucd = flag.String("ucd", "https://www.unicode.org/Public/"+xbidi.UnicodeVersion+"/ucd",
		"the character database: a URL or a directory")
	out = flag.String("o", "tables.go", "the file to write")
)

func main() {
	flag.Parse()
	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by "go run gen.go"; DO NOT EDIT.

package bidi

// unicodeVersion is the version of the character database these tables were
// generated from: the one golang.org/x/text's bidi classes come from.
const unicodeVersion = %q
`, xbidi.UnicodeVersion)
	mirrors(&b)
	brackets(&b)

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("formatting the tables: %v", err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
}

// fields calls f with the semicolon-separated fields of each data line of
// the named file, trimmed, and with comments removed.
func fields(name string, f func([]string)) {
	var r io.Reader
	src := *ucd + "/" + name
	if strings.HasPrefix(src, "http://") || strings.HasPrefix(src, "https://") {
		resp, err := http.Get(src)
		if err != nil {
			log.Fatal(err)
		}
		defer resp.Body.Close()
		if resp.StatusCode != http.StatusOK {
			log.Fatalf("%s: %s", src, resp.Status)
		}
		r = resp.Body
	} else {
		file, err := os.Open(path.Clean(src))
		if err != nil {
			log.Fatal(err)
		}
		defer file.Close()
		r = file
	}
	sc := bufio.NewScanner(r)
	for sc.Scan() {
		line, _, _ := strings.Cut(sc.Text(), "#")
		if strings.TrimSpace(line) == "" {
			continue
		}
		fs := strings.Split(line, ";")
		for i := range fs {
			fs[i] = strings.TrimSpace(fs[i])
		}
		f(fs)
	}
	if err := sc.Err(); err != nil {
		log.Fatal(err)
	}
}

func code(s string) rune {
	n, err := strconv.ParseUint(s, 16, 32)
	if err != nil {
		log.Fatalf("bad code point %q", s)
	}
	return rune(n)
}

func mirrors(b *bytes.Buffer) {
	type pair struct{ r, m rune }
	var ps []pair
	fields("BidiMirroring.txt", func(fs []string) {
		ps = append(ps, pair{code(fs[0]), code(fs[1])})
	})
	sort.Slice(ps, func(i, j int) bool { return ps[i].r < ps[j].r })
	fmt.Fprintf(b, `
// mirrors pairs each character that has a Bidi_Mirroring_Glyph with it, in
// order, for Mirror's binary search (BidiMirroring.txt).
var mirrors = [...]mirrorEntry{
`)
	for _, p := range ps {
		fmt.Fprintf(b, "\t{%#04x, %#04x},\n", p.r, p.m)
	}
	fmt.Fprintf(b, "}\n")
}

func brackets(b *bytes.Buffer) {
	type bracket struct {
		r, pair rune
		open    bool
	}
	var bs []bracket
	fields("BidiBrackets.txt", func(fs []string) {
		bs = append(bs, bracket{code(fs[0]), code(fs[1]), fs[2] == "o"})
	})
	sort.Slice(bs, func(i, j int) bool { return bs[i].r < bs[j].r })
	fmt.Fprintf(b, `
// brackets are the paired brackets, in order: each with its
// Bidi_Paired_Bracket, and whether it opens (BidiBrackets.txt).
var brackets = [...]bracketEntry{
`)
	for _, x := range bs {
		fmt.Fprintf(b, "\t{%#04x, %#04x, %v},\n", x.r, x.pair, x.open)
	}
	fmt.Fprintf(b, "}\n")
}
